# Generated by Django 5.0.3 on 2024-03-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_brand_tag_item_brand_category_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='free_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_shipping',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='item',
            name='min_shipping',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbnails'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/images')),
                ('order', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
