# Generated by Django 5.0.3 on 2024-03-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_delivery_item_featured_item_free_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbnails'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbnails'),
        ),
    ]
