# Generated by Django 5.0.2 on 2024-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('offer', models.PositiveSmallIntegerField(default=0)),
                ('overview', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='items/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
