# Generated by Django 5.0.2 on 2024-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_special_created_at_special_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
