# Generated by Django 5.0 on 2024-04-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_special_created_at_alter_special_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.special'),
        ),
    ]
