# Generated by Django 5.0.2 on 2024-04-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0012_alter_special_created_at_alter_special_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_total', models.PositiveSmallIntegerField(default=0)),
                ('sub_shipping', models.PositiveSmallIntegerField(default=0)),
                ('order_placed', models.BooleanField(default=True)),
                ('order_processing', models.BooleanField(default=False)),
                ('order_shipping', models.BooleanField(default=False)),
                ('order_rejected', models.BooleanField(default=False)),
                ('order_deliverd', models.BooleanField(default=False)),
                ('order_poked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('sale_price', models.PositiveSmallIntegerField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('shipping_price', models.PositiveSmallIntegerField()),
                ('return_requested', models.BooleanField(default=False)),
                ('return_note', models.CharField(blank=True, max_length=550, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
