# Generated by Django 5.0.3 on 2024-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
