# Generated by Django 5.0.2 on 2024-04-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_processing',
            field=models.BooleanField(default=True),
        ),
    ]
